class window:
    def refresh(self) -> None: ...
    def getch(self) -> int: ...
    def nodelay(self, flag: bool) -> None: ...
    def addstr(self, y: int, x: int, string: str) -> None: ...
    def getmaxyx(self) -> tuple[int]: ...