"""
Specification of the curses UI protocol as used by Ndo.
"""
# pylint: disable=missing-function-docstring

from typing import Protocol, overload, runtime_checkable


@runtime_checkable
class CursesWindow(Protocol):
    """
    Protocol for a curses window.
    This is used to allow for different implementations of the curses window.
    """

    def __init__(
        self,
        width: int = ...,
        height: int = ...,
        begin_y: int = ...,
        begin_x: int = ...,
    ) -> None: ...
    def getch(self) -> int: ...
    def move(self, new_y: int, new_x: int) -> None: ...
    @overload
    def addstr(self, text: str, attr: int = ...) -> None: ...
    @overload
    def addstr(self, y: int, x: int, text: str, attr: int = ...) -> None: ...
    def refresh(self) -> None: ...
    def getmaxyx(self) -> tuple[int, int]: ...
    def addch(self, y: int, x: int, char: str, attr: int = ...) -> None: ...
    def nodelay(self, flag: bool = ...) -> None: ...  # noqa: FBT001
    def box(self) -> None: ...
    def hline(self, y: int, x: int, ch: str, n: int) -> None: ...
    def clear(self) -> None: ...
    def timeout(self, delay: float) -> None: ...
    def keypad(self, flag: bool = ...) -> None: ...  # noqa: FBT001
    def attron(self, attr: int) -> None: ...
    def attroff(self, attr: int) -> None: ...
    def attrset(self, attr: int) -> None: ...
